baseURL: "http://blog.pagekeysolutions.com/"
languageCode: "en-us"
title: "PageKey Solutions Blog"
paginate: 5

params:
  keywords:
    - software engineering
    - programming
    - PageKey Solutions
    - PageKeySolutions
    - pks
    - code

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "https://pagekeysolutions.com/"
      weight: 2