baseURL: "http://blog.pagekeysolutions.com/"
languageCode: "en-us"
title: "PageKey Solutions Blog"
paginate: 10

params:
  keywords:
    - software engineering
    - programming
    - PageKey Solutions
    - PageKeySolutions
    - pks
    - code

menu:
  main:
  #   - name: "Blog Home"
  #     url: "/"
  #     weight: 1
    - name: "PageKey Solutions, LLC"
      url: "https://pagekeysolutions.com/"
      weight: 2