baseURL = "http://pagekeysolutions.com/"
languageCode = "en-us"
title = "PageKey Solutions"

[params]
    homeText = "Hello world"
    keywords = "software engineering, programming, web design, development, freelance developer, jekyll, PageKey Solutions, PageKeySolutions, pks, Stephen Grice, stephengrice, _stephengrice, freelance, line by line code, line by line, code"