baseURL: "http://pagekeysolutions.com/"
languageCode: "en-us"
title: "PageKey Solutions"

params:
  keywords:
    - software engineering
    - programming
    - PageKey Solutions
    - PageKeySolutions
    - pks
    - code

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Apps"
      url: "/apps/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Courses"
      url: "/courses/"
      weight: 4