site_name: My Docs
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    primary: blue
    accent: deep orange
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
  - search
  - tags:
      tags_file: tags.md
nav:
  - index.md
  - tags.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy; 2017 - <script>document.write(new Date().getFullYear())</script> PageKey Solutions, LLC
extra:
  social:
    - icon: fontawesome/brands/youtube 
      link: https://youtube.com/@PageKey
  alternate:
    - name: Español
      link: /es/
      lang: es
