authors:
  steve:
    name: Steve Grice
    description: Techie
    avatar: https://github.com/stephengrice.png
  eric:
    name: Eric Eaton
    description: Techie
    avatar: https://github.com/ericthomaseaton.png
