const id = "blog/2022/ftp/1.mdx";
						const collection = "post";
						const slug = "blog/2022/ftp/1";
						const body = "\nCoding is not scary! It's really easy to get started.\n\nSend this video to anyone you know who wants to get started with programming, but doesn't know how.\n\nimport BlogYoutubeVideo from '~/components/common/BlogYoutubeVideo.astro';\n\n<BlogYoutubeVideo videoId=\"rM8BZdOA_60\" />\n\n## Timestamps\n\n- 0:00 Coding is not scary\n- 1:24 Enter REPL.IT\n- 2:35 First line\n- 2:57 Break things (Errors)\n- 3:37 First Loop\n- 4:11 Make a design (Challenge)\n- 4:28 Recap\n\n## Summary\n\nThis video sets us up on the [REPL.IT website](https://replit.com) and gets us to the point where we have an interactive Python terminal. In a little over two minutes, we see how to write our first line of code:\n\n```python\nprint(\"Hello world\")\n```\n\nGet used to this message - it's usually the first thing you do to break ground in a new programming language. Now that we know we can print something to the screen, let's try adding some more messages:\n\n```python\nprint(\"Hello world\")\nprint(\"Hello world\")\nprint(\"Hello world\")\nprint(\"Hello world\")\n```\n\nCopy-pasting is great and all, but there's a better way. The true power of code comes from our ability to automate mundane tasks like this in an efficient way. With the following **loop**, we can execute our first line of code 20 times:\n\n```python\nfor i in range(20):\n    print(\"Hello world\")\n```\n\nNotice how easy it would be to change the 20 to something larger or smaller. Just a few keystrokes and you can go from 20 to 100,000. Imagine how much time (and space in your computer's memory) it would take to copy and paste that line 100,00 times!\n\nTo close, we'll make a little design to solidify what we've learned. This is a challenge for you - try to use the `print` statement to make something cool on the screen. As a bonus, see if you can incorporate a loop in your design. I'm not much of an artist, so what I came up with is pretty underwhelming:\n\n```python\nprint(\"  o  \")\nprint(\" ooo \")\nprint(\"ooooo\")\nprint(\" ooo \")\nprint(\"  o  \")\n```\n\nThe Sims, anyone?\n\nHope you enjoyed and learned something from this first lesson! Even if this was a piece of cake for you, consider sending it to someone who may benefit from a quick intro to coding - let's show people that it's not as hard as it sounds!\n\n";
						const data = {publishDate:new Date(1649289600000),title:"Get your feet wet | First Time Programmer 1",image:"http://i3.ytimg.com/vi/rM8BZdOA_60/hqdefault.jpg",category:"First Time Programmer",tags:["javascript","tutorial"],author:"Steve Grice"};
						const _internal = {
							type: 'content',
							filePath: "/home/runner/work/website/website/astrowind/src/content/post/blog/2022/ftp/1.mdx",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
